### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by kaede-jpg** [kaede-jpg/portfolio#28]
### 概要
家族・友人にダイエット（食事管理）を監視してもらうことができるサービス。
ダイエットを行う側は、食事を画像で記録することができ、もらったスタンプの意味ごと（怒り・賞賛・応援など）の集計と、それによる点数付け（マイナスも存在する）やコメントを閲覧できる。
 監視する側は、以下の機能を通してダイエットを監視し介入することができる。
 - 食事の記録を閲覧 ・励ましや怒り、アドバイスのスタンプやコメントを送る
 - スタンプやコメントを送る際、画像認識で記録された画像が何の食品かを判定し、そのカロリーに応じてキャラクターから出されたコメントを閲覧できる
 - 食事や運動の記録更新または記録漏れについての通知を受け取る

### 実装予定の機能
 - [ ] 会員登録機能
 - [ ] ログイン・ログアウト機能
 - [ ] ユーザー情報編集機能
 - [ ] コードの共有によるアカウント同士の連携機能
 - [ ] 食事画像の記録機能
 - [ ] コメント機能
 - [ ] スタンプ機能
 - [ ] スタンプの集計による点数付け機能

MVPリリース後
 - [ ] Google・LINEでのソーシャルログイン機能
 - [ ] LINEでの招待URL送信機能
 - [ ] LINE通知（更新/未更新リマインド）機能
 - [ ] 監視する側へのアドバイス機能 （画像解析・カロリー計算）

### 必要なページ
 - [ ] トップページ
 - [ ] ユーザー登録ページ
 - [ ] ログインページ
 - [ ] 監視側マイページ
 - [ ] 監視される側マイページ
 - [ ] ユーザー情報編集ページ
 - [ ] 連携用コード発行・入力ページ
 - [ ] LINE通知設定ページ
 - [ ] 投稿確認ページ
 - [ ] 投稿削除確認ページ
 - [ ] スタンプ投稿ページ
 - [ ] コメント一覧ページ
 - [ ] コメント投稿ページ
 - [ ] コメント編集ページ
 - [ ] 利用規約
 - [ ] プライバシーポリシー

**Comment by kaede-jpg** [comment]
RUNTEQアプリでのURL入力を誤ってしまったようで、「スケジュール・Issue管理」にGitHubのIssueが反映されていないようです。
上記のレビューに加え、こちらについても対応が必要でしたらご教示いただきたく存じます。

**Comment by Tsuchiya2** [comment]
Projectsにアクセスしましたが、看板・ストーリーポイント・issueが確認できませんでした。
カリキュラム確認の上、上記確認できる状態で提出をお願いいたします。

![image](https://github.com/kaede-jpg/portfolio/assets/61481161/a6aad2f0-b337-47b6-8667-84d44fd4a310)

> RUNTEQアプリでのURL入力を誤ってしまったようで、「スケジュール・Issue管理」にGitHubのIssueが反映されていないようです。

課題・開発を進めるうえでは問題ないので、そのまま進めてください。

**Comment by kaede-jpg** [comment]
大変失礼いたしました。
プロジェクトがリンクできていませんでした。
修正いたしましたので、ご確認のほどよろしくお願いします。

**Comment by kaede-jpg** [comment]
レビューありがとうございます。
修正いたしましたので、ご確認お願いいたします。
